name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.14
  lottie: ^3.1.2
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.1
  google_sign_in: ^6.2.1
  buttons_tabbar: ^1.3.13
  flutter_credit_card: ^4.0.1
  accordion: ^2.6.0
  ionicons: ^0.2.2
  line_awesome_flutter: ^3.0.1
  http: ^1.2.2
  provider: ^6.1.2
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/data/data.json
