// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyuN4_JRRQOfjA7JfTLDzMKqTygTLe2rY',
    appId: '1:328936844703:web:2f32f936d5be5ea93621aa',
    messagingSenderId: '328936844703',
    projectId: 'food-delivery-app-ad0c2',
    authDomain: 'food-delivery-app-ad0c2.firebaseapp.com',
    storageBucket: 'food-delivery-app-ad0c2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcYHvFLdjvYp11Z8tIZBOwgOjcpW-Gmt8',
    appId: '1:328936844703:android:8e02ce70fac1eb613621aa',
    messagingSenderId: '328936844703',
    projectId: 'food-delivery-app-ad0c2',
    storageBucket: 'food-delivery-app-ad0c2.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyuN4_JRRQOfjA7JfTLDzMKqTygTLe2rY',
    appId: '1:328936844703:web:cabf1435aeefef2a3621aa',
    messagingSenderId: '328936844703',
    projectId: 'food-delivery-app-ad0c2',
    authDomain: 'food-delivery-app-ad0c2.firebaseapp.com',
    storageBucket: 'food-delivery-app-ad0c2.appspot.com',
  );
}
